default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: 123

development:
  <<: *default
  database: soporteclebm_development

test: &test
  <<: *default
  database: soporteclebm_test

production:
  <<: *default
  database: soporteclebm_production
#  username: soporteclebm
#  password: <%= ENV['SOPRTECLEBM_DATABASE_PASSWORD'] %>
